# Site settings
title: Portfolio
subtitle: Where you can always see<br> what I am up to
email: pedroh.z.loures@gmail.com
linkedin: https://www.linkedin.com/in/pedroloures/
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
keywords: Modern, Blogging, Fun
author: Pedro Loures
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
collections:
  projects:
    order:
      - appfiat-treinamento.md
      - appvale-portotubarao.md
      - customdef.md
      - loneliness.md
      - blenderplug.md
      - appfiat-personaliza.md
      - mitologiaprog.md
      - chaveirinho.md
      - proceduraldung.md
      - animal-defense.md
      - digitalwonder.md
      - recifuturo.md